### ISSUE TITLE
tests do not compile

### ISSUE THREAD

**Issue by jean-pierreBoth** [liborty/sets#1]
error[E0061]: this function takes 1 argument but 0 arguments were supplied
   --> src/mutimpls.rs:41:40
    |
41  |                 self.index = self.data.hashsort_indexed();
    |                                        ^^^^^^^^^^^^^^^^-- an argument of type `&mut _` is missing
    |

**Comment by liborty** [comment]
Sorry about that. This was caused by a change in `indxvec` dependency. I have now issued a new version: Sets v1.2.0, which is fully compatible with the latest `indxvec 1.4.9`. However, it does introduce corresponding different usage of three methods. Please read the description in release notes at the bottom of the Readme file.
